all:
	g++ main.cpp grade.cpp Core.cpp Grad.cpp -o main

mem:
	g++ main_mem.cpp grade.cpp Core.cpp Grad.cpp -o main

handle:
	g++ main_handle.cpp Student_info.cpp grade.cpp Core.cpp Grad.cpp -o main

Handle:
	g++ main_Handle.cpp grade.cpp Core.cpp Grad.cpp -o main

Ptr:
	g++ main_Ptr.cpp grade.cpp Core.cpp Grad.cpp -o main

clean:
	rm main
